all:	j.java c.java
	javac --module-path /home/ask/Downloads/javafx-sdk-17.0.2/lib --add-modules javafx.controls j.java
	javac --module-path /home/ask/Downloads/javafx-sdk-17.0.2/lib --add-modules javafx.controls c.java
	java --module-path /home/ask/Downloads/javafx-sdk-17.0.2/lib --add-modules javafx.controls j &
	java --module-path /home/ask/Downloads/javafx-sdk-17.0.2/lib --add-modules javafx.controls c
