all:	Main.java StageController.java
	javac --module-path /home/ask/javafx-sdk-18/lib --add-modules javafx.controls,javafx.fxml *.java
	java --module-path /home/ask/javafx-sdk-18/lib --add-modules javafx.controls,javafx.fxml Main
